#spring.application.name=config-client
#spring.cloud.config.label=master
#spring.cloud.config.profile=dev
#spring.cloud.config.uri= http://localhost:8888/
#server.port=8881
server:
  port: 6002
spring:
  cloud:
    config:
      label: master
      profile: dev
      uri: http://127.0.0.1:6008/
