server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: microservice-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: microservice-ribbon-consumer
    api-b:
      path: /api-b/**
      serviceId: microserivce-feign-consumer