spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DEMAXIA/SpringcloudConfig/
          search-paths: respo
          username: 396985595@qq.com
          password: 1q2w3e4rt5
      label: master


server:
  port: 6001
